CREATE TABLE tableName 
(
    Kairat	varchar(300),
    	varchar(300),
    	varchar(300),
    	varchar(300),
    	varchar(300),
    	varchar(300),
    	varchar(300),
    	varchar(300)
);

INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('name ', 'surname', 'position', 'age', 'height', 'weight', 'country', 'contract');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Danil', 'Ustimenko', 'Goalkeeper', '22', '1.88', '', 'Kazakhstan', '2024');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Temirlan', 'Anarbekov', 'Goalkeeper', '19', '1.89', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Vadim', 'Ulyanov', 'Goalkeeper', '21', '1.88', '', 'Kazakhstan', '2023');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Macky', 'Bagnack', 'Centre-Back', '27', '1.87', '', 'Cameroon', '2023');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Viktor', 'Vasin', 'Centre-Back', '34', '1.92', '', 'Russia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Damir', 'Kasabulat', 'Centre-Back', '20', '1.81', '', 'Kazakhstan', '2023');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Egor', 'Tkachenko', 'Centre-Back', '19', '1.82', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Sergey', 'Keyler', 'Left-Back', '27', '1.8', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Sultanbek', 'Astanov', 'Right-Back', '23', '1.79', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Arsen', 'Buranchiev', 'Central Midfield', '21', '1.81', '', 'Kazakhstan', '2023');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Anton', 'Krachkovskiy', 'Central Midfield', '20', '1.66', '', 'Russia', '2023');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Adam', 'Adakhadzhiev', 'Central Midfield', '23', '1.76', '', 'Kazakhstan', '2023');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Daniyar', 'Usenov', 'Central Midfield', '21', '1.81', '', 'Kazakhstan', '2024');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Andrey', 'Ulshin', 'Central Midfield', '22', '1.83', '', 'Kazakhstan', '2024');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Gulzhigit', 'Alykulov', 'Left-Winger', '21', '1.69', '', 'Kyrgyzstan', '2023');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Erkebulan', 'Seydakhmet', 'Right-Winger', '22', '1.78', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Aybar', 'Abdulla', 'Right-Winger', '20', '1.76', '', 'Kazakhstan', '2023');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('João ', 'Paulo', 'Second Striker', '34', '1.7', '', 'Brazil', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Artur', 'Shushenachev', 'Centre-Forward', '24', '1.91', '', 'Kazakhstan', '2023');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Vyacheslav', 'Shvyrev', 'Centre-Forward', '21', '1.76', '', 'Kazakhstan', '2023');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Astana', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('name ', 'surname', 'position', 'age', 'height', 'weight', 'country', 'contract');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Marko', 'Milosevic', 'Goalkeeper', '31', '1.87', '', 'Serbia', '2023');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Aleksandr', 'Zarutskiy', 'Goalkeeper', '29', '1.92', '', 'Kazakhstan', '2023');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Danil', 'Podymskiy', 'Goalkeeper', '24', '1.9', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Abzal', 'Beysebekov', 'Centre-Back', '29', '1.87', '', 'Kazakhstan', '2023');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Denis', 'Polyakov', 'Centre-Back', '31', '1.84', '', 'Belarus', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Talgat', 'Kusyapov', 'Centre-Back', '23', '1.86', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Danylo', 'Beskorovaynyi', 'Centre-Back', '23', '1.94', '', 'Ukraine', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Artem', 'Rakhmanov', 'Centre-Back', '32', '1.95', '', 'Belarus', '2023');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Bryan', '', 'Left-back', '30', '1.77', '', 'Brazil', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Timur', 'Dosmagambetov', 'Left-Back', '33', '1.72', '', 'Kazakhstan', '2023');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Kamo', 'Hovhannisyan', 'Right-Back', '30', '1.76', '', 'Armenia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Mikhail', 'Gabyshev', 'Right-Back', '32', '1.85', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Islambek', 'Kuat', 'Defensive Midfield', '29', '1.79', '', 'Kazakhstan', '2024');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Aslanbek', 'Darabaev', 'Defensive Midfield', '33', '1.79', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Sultan', 'Sagnaev', 'Defensive Midfield', '22', '1.72', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Maks', 'Ebong', 'Central Midfield', '23', '1.8', '', 'Belarus', '2023');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Yuriy', 'Pertskukh', 'Central Midfield', '26', '1.86', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Jeremy', 'Manzorro', 'Attacking Midfield', '30', '1.73', '', 'France', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Pedro', 'Eugénio', 'Left Winger', '32', '1.72', '', 'Portugal', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Stanislav', 'Basmanov', 'Left Winger', '21', '1.79', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Marin', 'Tomasov', 'Right Winger', '35', '1.84', '', 'Croatia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Abat', 'Aymbetov', 'Centre-Forward', '27', '1.8', '', 'Kazakhstan', '2023');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Vladislav', 'Prokopenko', 'Centre-Forward', '22', '1.8', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('KASPIY AKTAU', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('name ', 'surname', 'position', 'age', 'height', 'weight', 'country', 'contract');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Nurlybek ', 'Ayazbaev', 'Goalkeeper', '31', '1.83', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Aleksey ', 'Kozlov', 'Goalkeeper', '23', '1.86', '', 'Russia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Olzhas ', 'Mukhanov', 'Goalkeeper', '24', '1.86', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Taras ', 'Bondarenko', 'Centre-Back', '30', '1.87', '', 'Ukraine', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Artem ', 'Baranovskyi', 'Centre-Back', '32', '1.9', '', 'Ukraine', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Viktor ', 'Dmitrenko', 'Centre-Back', '31', '1.9', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Erlan ', 'Kadyrbaev', 'Centre-Back', '31', '1.81', '', 'Ukraine', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Maksat ', 'Taykenov', 'Left-Back', '25', '1.69', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Anuar ', 'Bekmyrza', 'Left-Back', '21', '1.75', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Miras ', 'Tuliev', 'Right-Back', '28', '1.78', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Duman ', 'Narzildaev', 'Defensive Midfield', '29', '1.78', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Chafik ', 'Tigroudja', 'Central Midfield', '30', '1.76', '', 'France', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Nikola ', 'Cuckic', 'Central Midfield', '25', '1.75', '', 'Serbia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Kuandyk ', 'Nursultanov', 'Central Midfield', '23', '1.75', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Rati ', 'Ardazishvili', 'Attacking Midfield', '24', '1.77', '', 'Georgia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Erkebulan ', 'Nurgaliev', 'Attacking Midfield', '29', '1.7', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Rúben ', 'Brígido', 'Left Winger', '31', '1.72', '', 'Portugal', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Ivan ', 'Pesic', 'Left Winger', '30', '1.84', '', 'Croatia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Pavel ', 'Kireenko', 'Left Winger', '28', '1.75', '', 'Russia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Alisher ', 'Suley', 'Left Winger', '26', '1.78', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Maksim ', 'Vaganov', 'Left Winger', '22', '1.83', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Darkhan ', 'Berdibek', 'Left Winger', '18', '1.79', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Aslan ', 'Adil', 'Right Winger', '24', '1.74', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Ruan ', 'Teles', 'Right Winger', '24', '1.72', '', 'Brasil', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Bakdaulet ', 'Konlimkos', 'Right Winger', '21', '1.7', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Almas ', 'Armenov', 'Centre-Forward', '30', '1.7', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('QYZYLJAR PETROPAVLOVSK', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('name ', 'surname', 'position', 'age', 'height', 'weight', 'country', 'contract');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Miroslav', 'Lobantsev', 'Goalkeeper', '27', '1.89', '', ' Russia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Vadim', 'Petrov', 'Goalkeeper', '22', '1.88', '', 'Kazakhstan', '2023');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Vladimir', 'Loginovskiy', 'Goalkeeper', '37', '1.93', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Aldiyar', 'Zhumabaev', 'Goalkeeper', '20', '1.9', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Mateo', 'Muzek', 'Centre-Back', '27', '1.83', '', 'Croatia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Oleg', 'Murachev', 'Centre-Back', '27', '1.82', '', 'Russia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Mark ', 'Gurman', 'Centre-Back', '33', '1.79', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Valeri ', 'Karshakevich', 'Centre-Back', '34', '1.93', '', 'Belarus', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Viktor ', 'Zyabko', 'Centre-Back', '25', '1.85', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Yuriy ', 'Bushman', 'Left-Back', '32', '1.78', '', 'Ukraine', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Dmitri ', 'Schmidt', 'Right-Back', '28', '1.75', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Aldair ', 'Adilov', 'Right-Back', '20', '1.72', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Gian ', 'Martins', 'Defensive Midfield', '29', '1.84', '', 'Brazil', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Erkin ', 'Tapalov', 'Defensive Midfield', '29', '1.8', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Moussa ', 'Koné', 'Defensive Midfield', '32', '1.82', '', 'Cote d\'Ivoire', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Sergey ', 'Tikhonovskiy', 'Defensive Midfield', '32', '1.75', '', 'Belarus', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Pablo ', 'Podio', 'Central Midfield', '33', '1.8', '', 'Argentina', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Rafail ', 'Ospanov', 'Central Midfield', '24', '1.81', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Evgeniy ', 'Kozlov', 'Left Winger', '27', '1.78', '', 'Russia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Brandao', '', 'Left Winger', '26', '1.8', '', 'Brazil', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Darko ', 'Zoric', 'Right Winger', '29', '1.89', '', 'Montenegro', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Pavel ', 'Yakovlev', 'Right Winger', '31', '1.8', '', 'Russia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Elguja ', 'Lobjanidze', 'Centre-Forward', '30', '1.93', '', 'Georgia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Maksim ', 'Chikanchi', 'Centre-Forward', '24', '1.84', '', 'Russia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Timur ', 'Muldinov', 'Centre-Forward', '29', '1.8', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('FK TARAZ', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('name ', 'surname', 'position', 'age', 'height', 'weight', 'country', 'contract');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Mukhammedzhan ', 'Seysen', 'Goalkeeper', '23', '1.9', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Denis ', 'Kavlinov', 'Goalkeeper', '27', '1.91', '', 'Russia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Dzhurakhon ', 'Babakhanov', 'Goalkeeper', '30', '1.9', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Nurlan ', 'Dairov', 'Centre-Back', '27', '1.81', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Luka ', 'Gadrani', 'Centre-Back', '25', '1.85', '', 'Georgia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Eldos ', 'Akhmetov', 'Centre-Back', '32', '1.87', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Bekzat ', 'Shadmanov', 'Centre-Back', '25', '1.89', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Berik ', 'Aytbaev', 'Centre-Back', '31', '1.84', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Zhalgas ', 'Zhaksylykov', 'Centre-Back', '21', '1.89', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Alex ', 'Júnior', 'Left-Back', '29', '1.83', '', 'Haiti', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Kuanysh ', 'Kalmuratov', 'Left-Back', '26', '1.78', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Maksat ', 'Amirkhanov', 'Right-Back', '30', '1.72', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Adilet ', 'Kenesbek', 'Right-Back', '26', '1.8', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Ermek ', 'Kuantaev', 'Right-Back', '32', '1.74', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Milen ', 'Gamakov', 'Defensive Midfield', '28', '1.89', '', 'Bulgaria', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Marat ', 'Shakhmetov', 'Defensive Midfield', '33', '1.82', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Almas ', 'Sapargaliev', 'Defensive Midfield', '28', '1.83', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Bektas ', 'Nurdaulet', 'Defensive Midfield', '24', '1.8', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Abzal ', 'Taubay', 'Central Midfield', '27', '1.75', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Ersultan ', 'Kaldybekov', 'Central Midfield', '20', '1.85', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Erkebulan ', 'Toybekov', 'Left Winger', '20', '1.8', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Dinmukhamed ', 'Karaman', 'Right Winger', '22', '1.78', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Zhakyp ', 'Kozhamberdy', 'Right Winger', '30', '1.83', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Abylaykhan ', 'Zhumabek', 'Centre-Forward', '20', '1.87', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Maksym ', 'Degtyarov', 'Centre-Forward', '29', '1.85', '', 'Ukraine', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('ORDABASY SHYMKENT', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('name ', 'surname', 'position', 'age', 'height', 'weight', 'country', 'contract');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Bekkhan ', 'Shayzada', 'Goalkeeper', '24', '1.88', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Timurbek ', 'Zakirov', 'Goalkeeper', '26', '1.89', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Kazhymukan ', 'Tolepbergen', 'Goalkeeper', '22', '1.85', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Dominik ', 'Dinga', 'Centre-Back', '24', '1.86', '', 'Serbia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Luka ', 'Gadrani', 'Centre-Back', '25', '1.85', '', 'Georgia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Sagadat ', 'Tursynbay', 'Centre-Back', '23', '1.88', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Odil ', 'Abdumazhidov', 'Centre-Back', '21', '1.85', '', 'Uzbekistan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Karam ', 'Sultanov', 'Centre-Back', '26', '1.95', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Igor ', 'Klyushkin', 'Right-Back', '19', '1.83', '', 'Russia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Oleksandr ', 'Batyshchev', 'Defensive Midfield', '31', '1.74', '', 'Ukraine', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Victor ', 'Braga', 'Defensive Midfield', '21', '1.75', '', 'Brasil', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Dmitriy ', 'Borodin', 'Central Midfield', '23', '1.94', '', 'Belarus', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Murodzhon ', 'Khalmatov', 'Central Midfield', '19', '1.79', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Adilkhan ', 'Dobay', 'Right Midfield', '20', '1.83', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Samat ', 'Shamshi', 'Left Midfield', '26', '1.78', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Nikita ', 'Shershnev', 'Left Midfield', '20', '1.75', '', 'Russia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Elkhan ', 'Astanov', 'Left Winger', '22', '1.86', '', 'Kazakhstan', '2025');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Shakhboz ', 'Umarov', 'Left Winger', '23', '1.82', '', 'Uzbekistan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Maksim ', 'Fedin', 'Right Winger', '26', '1.75', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Akmal ', 'Bakhtiyarov', 'Right Winger', '24', '1.69', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Zikrillo ', 'Sultaniyazov', 'Right Winger', '18', '1.82', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Batyrkhan ', 'Tazhibay', 'Right Winger', '21', '1.74', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Khamza ', 'Yakudi', 'Right Winger', '18', '1.8', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Serge ', 'Nyuiadzi', 'Centre-Forward', '31', '1.81', '', 'Togo', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Vsevolod ', 'Sadovskiy', 'Centre-Forward', '26', '1.95', '', 'Belarus', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Luizinho ', 'Guedes', 'Centre-Forward', '23', '1.8', '', 'Brasil', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Shakhter Karaganda', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('name ', 'surname', 'position', 'age', 'height', 'weight', 'country', 'contract');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Igor ', 'Shatskiy', 'Goalkeeper', '33', '1.85', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Egor ', 'Tsuprikov', 'Goalkeeper', '25', '1.9', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Igor ', 'Trofimets', 'Goalkeeper', '26', '1.94', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Danila ', 'Karpikov', 'Goalkeeper', '18', '1.93', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Djordje ', 'Cosic', 'Centre-Back', '27', '1.87', '', 'Bosnia-Herzegovina', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Aleksandr ', 'Poznyak', 'Centre-Back', '28', '1.86', '', 'Belarus', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Tair ', 'Nurseitov', 'Centre-Back', '22', '1.98', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Miram ', 'Sapanov', 'Centre-Back', '36', '1.83', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Ivan ', 'Graf', 'Centre-Back', '35', '1.94', '', 'Croatia ', '2023');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Temur ', 'Mustafin', 'Left-Back', '27', '1.83', '', 'Russia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Filip ', 'Gligorov', 'Right-Back', '29', '1.81', '', 'North Macedonia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Stefan ', 'Bukorac', 'Defensive Midfield ', '31', '1.93', '', 'Serbia', '2023');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Róger ', 'Cañas', 'Defensive Midfield ', '32', '1.9', '', 'Colombia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Almas ', 'Tyulyubay', 'Defensive Midfield ', '21', '1.81', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Ruslan ', 'Tutkyshev', 'Defensive Midfield ', '23', '1.8', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Farkhat ', 'Musabekov', 'Central Midfield ', '28', '1.75', '', 'Kyrgyzstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Abylaykhan ', 'Nazymkhanov', 'Central Midfield ', '20', '1.84', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Ibragim ', 'Dadaev', 'Attacking Midfield ', '20', '1.78', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Roman ', 'Murtazaev', 'Left Winger ', '29', '1.88', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Akmal ', 'Bakhtiyarov', 'Right Winger', '24', '1.69', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Evgeniy ', 'Kobzar', 'Left Winger ', '30', '1.72', '', 'Russia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Toktar ', 'Zhangylyshbay', 'Right Winger', '29', '1.89', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Temur ', 'Chogadze', 'Right Winger', '24', '1.77', '', 'Georgia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Mykola ', 'Kovtalyuk', 'Centre-Forward', '27', '1.91', '', 'Ukraine ', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Aydos ', 'Tattybaev', 'Centre-Forward', '32', '1.86', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Ivan ', 'Sviridov', 'Centre-Forward', '20', '1.84', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Shyngys ', 'Flyuk', 'Centre-Forward', '20', '1.78', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('aksu', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('name ', 'surname', 'position', 'age', 'height', 'weight', 'country', 'contract');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Marsel ', 'Islamkulov', 'Goalkeeper', '28', '1.88', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Yevgeniy ', 'Kucherenko', 'Goalkeeper', '23', '1.92', '', 'Ukraine', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Mikhail', 'Golubnichiy', 'Goalkeeper', '27', '1.88', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Faith', 'Obilor', 'Centre-Back', '31', '1.89', '', 'Nigeria', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Ular', 'Zhaksybaev', 'Centre-Back', '27', '1.8', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Artem', 'Popov', 'Centre-Back', '24', '1.88', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Oleksiy', 'Dytyatyev', 'Centre-Back', '33', '1.96', '', 'Ukraine', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Gafurzhan', 'Suyumbaev', 'Left-Back', '32', '1.75', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Grigoriy', 'Sartakov', 'Left-Back', '28', '1.85', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Aleksey ', 'Skvortsov', 'Left-Back', '22', '1.78', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Zhaksylyk', 'Kenzhebaev', 'Left-Back', '25', '1.75', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Kayrat ', 'Zhyrgalbek uulu', 'Right-Back', '29', '1.77', '', 'Kyrgyzstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Islam ', 'Zhilov', 'Right-Back', '24', '1.74', '', 'Russia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Ruslan ', 'Esimov', 'Right-Back', '32', '1.82', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Gilson ', 'Costa', 'Defensive Midfield', '26', '1.85', '', 'Portugal', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Mikhail ', 'Bakaev', 'Defensive Midfield', '35', '1.75', '', 'Russia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Lazar ', 'Zlicic', 'Central Midfield', '25', '1.82', '', 'Serbia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Zhaslan ', 'Kairkenov', 'Central Midfield', '22', '1.75', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Anatoliy', 'Krasotin', 'Central Midfield', '22', '1.73', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Aslanbek ', 'Kakimov', 'Left Winger', '29', '1.77', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Georgiy ', 'Zakharenko', 'Left Winger', '24', '1.75', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Toni ', 'Silva', 'Right Winger', '29', '1.79', '', 'Guinea-Bissau', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Erkebulan ', 'Tungyshbayev', 'Right Winger', '27', '1.82', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Damir ', 'Marat', 'Right Winger', '21', '1.75', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Tamerlan ', 'Agimanov', 'Right Winger', '16', '1.86', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Miras ', 'Turlybek', 'Centre-Forward', '21', '1.9', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Arman ', 'Smailov', 'Centre-Forward', '25', '1.86', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Marlen ', 'Aymanov', 'Centre-Forward', '23', '1.91', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Turan', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('name ', 'surname', 'position', 'age', 'height', 'weight', 'country', 'contract');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Erzhan ', 'Tokotaev', 'Goalkeeper', '22', '1.89', '', 'Kyrgyzstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Dinmukhammed ', 'Zhomart', 'Goalkeeper', '21', '1.88', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Bekzhan ', 'Toktarbay', 'Goalkeeper', '25', '1.86', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Olzhas ', 'Kerimzhanov', 'Centre-Back', '33', '1.89', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Timur ', 'Rudoselskiy', 'Centre-Back', '27', '1.93', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Kasymzhan ', 'Taipov', 'Centre-Back', '27', '1.8', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Syrbay ', 'Maulen', 'Centre-Back', '23', '1.87', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Raphael ', 'Koroma', 'Centre-Back', '22', '1.9', '', 'Sierra Leone', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Zvonko ', 'Ceklic', 'Left-Back', '23', '1.9', '', 'Montenegro', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Andrey ', 'Zaleskiy', 'Right-Back', '31', '1.8', '', 'Belarus', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Lev', 'Skvortsov', 'Right-Back', '22', '1.8', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Ruslan ', 'Zhanysbaev', 'Right-Back', '26', '1.78', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Abdoulaye ', 'Diakhate', 'Defensive Midfield', '34', '1.81', '', 'Senegal', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Mikhail ', 'Bashilov', 'Defensive Midfield', '29', '1.8', '', 'Russia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Oleg ', 'Evdokimov', 'Central Midfield', '28', '1.77', '', 'Belarus', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Sanzhar ', 'Satanov', 'Attacking Midfield', '21', '1.85', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Azat ', 'Nurgaliev', 'Left Winger', '36', '1.73', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Shokhan ', 'Abzalov', 'Left Winger', '29', '1.82', '', 'Kazakhstan', '2023');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Aliyar ', 'Mukhammed', 'Left Winger', '21', '1.9', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Arman ', 'Nusip', 'Left Winger', '28', '1.8', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Temirlan ', 'Amirov', 'Left Winger', '25', '1.78', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Bekzat ', 'Kabylan', 'Left Winger', '26', '1.62', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Alen ', 'Aymanov', 'Left Winger', '20', '1.78', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Jô ', 'Santos', 'Right Winger', '31', '1.74', '', 'Brazil', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Artem ', 'Gurenko', 'Right Winger', '28', '1.71', '', 'Belarus', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Kehinde ', 'Fatai', 'Centre-Forward', '32', '1.8', '', 'Nigeria', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Samir ', 'Fazli', 'Centre-Forward', '31', '1.85', '', 'North Macedonia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Tanat ', 'Nuserbaev', 'Centre-Forward', '35', '1.75', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Bakdaulet ', 'Zulfikarov', 'Centre-Forward', '21', '1.82', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Atyrau', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('name ', 'surname', 'position', 'age', 'height', 'weight', 'country', 'contract');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Aram ', 'Hayrapetyan', 'Goalkeeper', '35', '1.92', '', 'Armenia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Azamat ', 'Zhomartov', 'Goalkeeper', '27', '1.93', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Ilya ', 'Karavaev', 'Goalkeeper', '27', '1.86', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Nikolay ', 'Tarasov', 'Centre-Back', '24', '1.87', '', 'Russia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Matheus ', 'Bissi', 'Centre-Back', '31', '1.88', '', 'Brazil', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Ravil ', 'Ibragimov', 'Centre-Back', '21', '1.86', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Pawel ', 'Baranowski', 'Centre-Back', '32', '1.91', '', 'Poland', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Daniyar ', 'Urda', 'Centre-Back', '19', '1.84', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Amandyk ', 'Nabikhanov', 'Right-Back', '24', '1.83', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Aleksandr ', 'Sokolenko', 'Right-Back', '25', '1.81', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Adi ', 'Adambaev', 'Right-Back', '21', '1.85', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Todor ', 'Petrovic', 'Defensive Midfield', '28', '1.9', '', 'Serbia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Domantas ', 'Antanavicius', 'Defensive Midfield', '23', '1.77', '', 'Lithuania', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Altynbek ', 'Saparov', 'Central Midfield', '27', '1.74', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Rinat ', 'Dzhumatov', 'Central Midfield', '25', '1.74', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Soslan ', 'Takulov', 'Left Midfield', '27', '1.78', '', 'Russia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Dmitriy', 'Pletnev', 'Left Winger', '24', '1.78', '', 'Russia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Yuri ', 'Zavezen', 'Left Winger', '26', '1.76', '', 'Russia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Asylbek ', 'Seytkaliev', 'Left Winger', '30', '1.68', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Khusrav ', 'Toirov', 'Left Winger', '18', '1.78', '', 'Tajikistan', '2023');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Andrija ', 'Filipovic', 'Right Winger', '25', '1.81', '', 'Croatia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Demir ', 'Imeri', 'Right Winger', '26', '1.75', '', 'North Macedonia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Pavel ', 'Dolgov', 'Centre-Forward', '26', '1.85', '', 'Russia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Piotr', 'Grzelczak', 'Centre-Forward', '34', '1.86', '', 'Poland', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Denis ', 'Mitrofanov', 'Centre-Forward', '20', '1.84', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Akzhayik Uralsk', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('name ', 'surname', 'position', 'age', 'height', 'weight', 'country', 'contract');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Kostyantyn', 'Makhnovskyi', 'Goalkeeper', '33', '1.9', '', 'Ukraine', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Stefan', 'Sicaci', 'Goalkeeper', '34', '1.96', '', 'Moldova', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Rodion', 'Syamuk', 'Goalkeeper', '33', '1.88', '', 'Belarus', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Amir', 'Bilali', 'Centre-Back', '28', '1.89', '', 'Albania', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Vitaliy', 'Pryndeta', 'Centre-Back', '29', '1.97', '', 'Ukraine', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Sergey', 'Shustikov', 'Centre-Back', '33', '1.88', '', 'Russia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Vladimir ', 'Pokatilov', 'Centre-Back', '29', '1.92', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Roman', 'Bozhko', 'Centre-Back', '20', '1.9', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Bauyrzhan ', 'Omarov', 'Left-Back', '32', '1.81', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Pavel ', 'Nazarenko', 'Right-Back', '27', '1.74', '', 'Belarus', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Ruslan ', 'Khairov', 'Right-Back', '32', '1.74', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Eldar ', 'Abdrakhmanov', 'Right-Back', '35', '1.75', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Rafael ', 'Sabino', 'Defensive Midfield', '26', '1.78', '', 'Brazil', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Aleksandr ', 'Vulfov', 'Central Midfield', '24', '1.83', '', 'Russia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Maksym ', 'Kalenchuk', 'Central Midfield', '32', '1.83', '', 'Ukraine', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Batyr ', 'Mukashev', 'Central Midfield', '19', '1.8', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Petros ', 'Avetisyan', 'Attacking Midfield', '26', '1.78', '', 'Armenia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Luka ', 'Imnadze', 'Left Winger', '25', '1.84', '', 'Georgia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Ilya ', 'Kovalenko', 'Left Winger', '32', '1.78', '', 'Ukraine', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Zaven ', 'Badoyan', 'Left Winger', '32', '1.72', '', 'Armenia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Rysbek ', 'Konyrov', 'Left Winger', '20', '1.86', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Artur ', 'Gazdanov', 'Right Winger', '30', '1.8', '', 'Russia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Ardak ', 'Saulet', 'Right Winger', '25', '1.69', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Bekzat ', 'Imangazeev', 'Right Winger', '21', '1.73', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Saveliy ', 'Glazunov', 'Right Winger', '21', '1.71', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Oralkhan ', 'Omirtaev', 'Centre-Forward', '24', '1.87', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Toma ', 'Tabatadze', 'Centre-Forward', '30', '1.92', '', 'Georgia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Maktaaral', '', '', '', '', '', '', '');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('name ', 'surname', 'position', 'age', 'height', 'weight', 'country', 'contract');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Sergiy ', 'Litovchenko', 'Goalkeeper', '35', '1.92', '', 'Ukraine', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Zhandar ', 'Zhangaliev', 'Goalkeeper', '23', '1.91', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Ramil ', 'Nurmukhametov', 'Goalkeeper', '34', '1.82', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Artiom ', 'Rozgoniuc', 'Centre-Back', '27', '1.85', '', 'Moldova', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Egor ', 'Potapov', 'Centre-Back', '29', '1.94', '', 'Russia', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Dramane ', 'Koné', 'Centre-Back', '32', '1.83', '', 'Cote d\'Ivoire', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Ruslan ', 'Yudenkov', 'Centre-Back', '35', '1.88', '', 'Belarus', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Sagi ', 'Sovet', 'Left-Back', '22', '1.75', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Artur ', 'Zapadnya', 'Left-Back', '32', '1.83', '', 'Ukraine', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Pavel ', 'Chikida', 'Right-Back', '27', '1.78', '', 'Belarus', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Dierzhon ', 'Aripov', 'Right-Back', '25', '1.74', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Aleksey ', 'Nosko', 'Defensive Midfield', '26', '1.88', '', 'Belarus', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Jakha Yao', 'Leonard', 'Defensive Midfield', '20', '1.78', '', 'Cote d\'Ivoire', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Odilzhon ', 'Abdurakhmanov', 'Central Midfield', '26', '1.85', '', 'Kyrgyzstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Sekou ', 'Doumbia', 'Central Midfield', '28', '1.84', '', 'Cote d\'Ivoire', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Meyrambek ', 'Serikbay', 'Central Midfield', '22', '1.75', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Aléx ', 'Bruno', 'Left Winger', '29', '1.73', '', 'Brazil', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Galymzhan ', 'Kenzhebek', 'Left Winger', '19', '1.77', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Beknur ', 'Ryskul', 'Left Winger', '24', '1.7', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Nurzhigit ', 'Smatov', 'Left Winger', '26', '1.77', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Billal ', 'Sebaihi', 'Right Winger', '30', '1.79', '', 'France', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Zhan-Ali', 'Payruz', 'Right Winger', '23', '1.85', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Ramazan ', 'Karimov', 'Centre-Forward', '23', '1.9', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Bekzat ', 'Zhaksybayuly', 'Centre-Forward', '27', '1.84', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Sultanbek ', 'Duyseshov', 'Centre-Forward', '21', '1.82', '', 'Kazakhstan', '2022');
INSERT INTO tableName (Kairat, , , , , , , ) VALUES ('Dunaybek ', 'Ayankhan', 'Centre-Forward', '22', '1.87', '', 'Kazakhstan', '2022');
